insert into book values(1, 10, 'Alyssa Wong', 'Comics', 'Phillip Tan', 'Michael Yg', 'A.X.E.: Iron Fist (2022) #1');
insert into book values(2, 10, 'Ram. V.', 'Comics', 'Bryan Hitch', null, 'Venom (2021) #11');
insert into book values(3, 10, 'Benjamin Percy', 'Comics', 'Kael Ngu', 'Cory Smith', 'Ghost Rider (2022) #7');
insert into book values(4, 11, 'Kieron Gillen', 'Comics', 'Esad Pibic', ' Guiu Vilanova', 'A.X.E.: Death to the Mutants (2022) #3');
insert into book values(5, 9, 'Si Spurrier', 'Comics', 'Dike Ruan', 'Rafael Pimentel', 'Legion of X (2022) #6');
insert into book values(6, 14, 'Takashi Okazaki', 'Comics', null, null, 'STAR WARS: VISIONS 1 (2022) #1');
insert into book values(7, 17, 'Benjamin Percy', 'Comics', 'Joshua Cassara', 'Robert Gill', 'X-FORCE (2019) #32');
insert into book values(8, 25, 'John Redden', 'Textbook', null, null, 'Advanced Algebra v.1.0');
insert into book values(9, 30, 'Stuart Murphy', 'Textbook', null, null, 'The Art of Polynomial Interpolation');
insert into book values(10, 22, 'Ivan G. Zaigralin', 'Textbook', null, null, 'Basic Algebra with Applications - 5th Edition');
insert into book values(11, 22, 'Jogindra M. Wadehra', 'Textbook', null, null, 'Mathematics for Biomedical Physics');
insert into book values(12, 35, 'Terence Patric Dolan', 'Dictionary', null, null, 'A Dictionary of Hiberno English');
insert into book values(13, 50, 'Nicholas Awde', 'Dictionary', null, null, 'Hippocrene Practical Dictionary');
insert into book values(14, 34, 'Ursula Martini', 'Dictionary', null, null, 'Spanish-English Dictionary');
insert into book values(15, 23, 'Joshua Bloch', 'Programming', null, null, 'Effective Java');
insert into book values(16, 20, 'Kathy Sierra', 'Programming', 'Bert Bates', null, 'Head First Java');
insert into book values(17, 30, 'Brian Goetz', 'Programming', null, null, 'Java Concurrency in Practice');
insert into book values(18, 30, 'Russ Olsen', 'Programming', null, null, 'Eloquent Ruby');
insert into book values(19, 38, 'Jon Skeet', 'Programming', null, null, 'C# in Depth');
insert into book values(20, 43, 'Brian W. Kernighan', 'Programming', 'Dennis M. Ritchie', null, 'C Programming Language');
insert into book values(21, 21, 'Stanley B. Lippman', 'Programming', 'Josee Lajoie', 'Barbara E. Moo', 'C++ Primer');
insert into book values(22, 16, 'Jane Austen', 'Classic', null, null, 'Pride and Prejudice');
insert into book values(23, 20, 'F. Scott Fitzgerald', 'Classic', null, null, 'The Great Gatsby');
insert into book values(24, 24, 'Jean Rhys', 'Classic', null, null, 'Wide Sargasso Sea');
insert into book values(25, 20, 'Dodie Smith', 'Classic', null, null, 'I Capture The Castle');